project:
  type: website

website:
  title: "it's bona behind"
  site-url: https://itsbonabehind.com 
  description: "Personal blog by Jueun Bona Lee"
  navbar:
    right:
      #- text: about
      #  href: about.qmd
      - text: posts
        href: posts.qmd
      #- icon: github
      #  href: https://github.com/
      #- icon: twitter
      #  href: https://twitter.com
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css

editor: visual

